version: "3"
services:
  trainer:
    image: trainer:latest
    build:
      context: .
      dockerfile: dockerfiles/train_model.dockerfile
    volumes:
      - .:/app  
    command: uv run train /app/configs/vit_gpt2.yaml
  # predict:
  #   image: predict:latest
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/predict_model.dockerfile