name: "Setup Python and UV"
description: "Setup Python and install dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.10"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.1"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: 'true'
        cache-suffix: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --frozen
      shell: bash