name:

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install huggingface_hub
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Clone HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/hrangi/imagecaption space-repo

      - name: Sync files into Space
        run: rsync -av --exclude='.git' ./ space-repo/

      - name: Commit & Push
        working-directory: space-repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "CI: update Streamlit app"
            git push https://hrangi:${HF_TOKEN}@huggingface.co/spaces/hrangi/imagecaption main --force
          fi

