name: Run linting and formatting

on:
  push:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
      fail-fast: false
    defaults:
      runs:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check format
        run: uv run ruff format --check

      - name: Check lint
        run: uv run ruff check


